## autogenerated
self: super: let
  common = {
    applicationName = "firefox";
    pname = "firefox-bin";
  };
in {
  firefox-stable = let
    version = "147.0";
    sources = {
      url = "https://download.cdn.mozilla.net/pub/firefox/releases/147.0/linux-aarch64/en-US/firefox-147.0.tar.xz";
      sha512 = "0b5c1ca85dcca2ce9ae36cadcedd71f6c0269984db005f04e2638020681357aea9c916aa1e8bac12d0951be7185223c498a471086bd91ed25c5e1a82060e1d24";
    };
  in
    super.wrapFirefox ((self.firefox-bin-unwrapped.override {
      generated = {
        inherit version sources;
      };
    }).overrideAttrs (old: {src = super.fetchurl sources;}))
    common;
  firefox-esr = let
    version = "140.7.0esr";
    sources = {
      url = "https://download.cdn.mozilla.net/pub/firefox/releases/140.7.0esr/linux-aarch64/en-US/firefox-140.7.0esr.tar.xz";
      sha512 = "0b5c1ca85dcca2ce9ae36cadcedd71f6c0269984db005f04e2638020681357aea9c916aa1e8bac12d0951be7185223c498a471086bd91ed25c5e1a82060e1d24";
    };
  in
    super.wrapFirefox ((self.firefox-bin-unwrapped.override {
      generated = {
        inherit version sources;
      };
    }).overrideAttrs (old: {src = super.fetchurl sources;}))
    common;
  firefox-devel = let
    version = "148.0b1";
    sources = {
      url = "https://download.cdn.mozilla.net/pub/firefox/releases/148.0b1/linux-aarch64/en-US/firefox-148.0b1.tar.xz";
      sha512 = "368b699fc57f5500ae5a6a74c20e1520ab4de6750935ce3a8cf6438f1399c1a9a1c80271caf11cb0fd4df76f8910f3a672d46c2bf6e50517519088c603a1cf31";
    };
  in
    super.wrapFirefox ((self.firefox-bin-unwrapped.override {
      generated = {
        inherit version sources;
      };
    }).overrideAttrs (old: {src = super.fetchurl sources;}))
    common;
}
