## autogenerated
self: super: let
  common = {
    applicationName = "firefox";
    pname = "firefox-bin";
  };
in {
  firefox-stable = let
    version = "152.0";
    sources = {
      url = "https://download.cdn.mozilla.net/pub/firefox/releases/152.0/linux-aarch64/en-US/firefox-152.0.tar.xz";
      sha512 = "b44610559deecc174fd08189d82c80309b6adadb4fa40c5b77cd44b743b778cfc31140de6add76e3f33efcf6640e8fb9c1c5da6bc08de30657cff9364c04ed19";
    };
  in
    super.wrapFirefox ((self.firefox-bin-unwrapped.override {
      generated = {
        inherit version sources;
      };
    }).overrideAttrs (old: {src = super.fetchurl sources;}))
    common;
  firefox-esr = let
    version = "140.12.0esr";
    sources = {
      url = "https://download.cdn.mozilla.net/pub/firefox/releases/140.12.0esr/linux-aarch64/en-US/firefox-140.12.0esr.tar.xz";
      sha512 = "b44610559deecc174fd08189d82c80309b6adadb4fa40c5b77cd44b743b778cfc31140de6add76e3f33efcf6640e8fb9c1c5da6bc08de30657cff9364c04ed19";
    };
  in
    super.wrapFirefox ((self.firefox-bin-unwrapped.override {
      generated = {
        inherit version sources;
      };
    }).overrideAttrs (old: {src = super.fetchurl sources;}))
    common;
  firefox-devel = let
    version = "153.0b1";
    sources = {
      url = "https://download.cdn.mozilla.net/pub/firefox/releases/153.0b1/linux-aarch64/en-US/firefox-153.0b1.tar.xz";
      sha512 = "559d43324003db554c2aeefafb7968e5ea6e744e0de1e1ca0387e932c33b14ad8cff13d009df85826388dd24910d76ab6d3c85c0524d0fc4c2adeb66058b3d74";
    };
  in
    super.wrapFirefox ((self.firefox-bin-unwrapped.override {
      generated = {
        inherit version sources;
      };
    }).overrideAttrs (old: {src = super.fetchurl sources;}))
    common;
}
