## autogenerated
self: super: let
  common = {
    applicationName = "firefox";
    pname = "firefox-bin";
  };
in {
  firefox-stable = let
    version = "145.0";
    sources = {
      url = "https://download.cdn.mozilla.net/pub/firefox/releases/145.0/linux-aarch64/en-US/firefox-145.0.tar.xz";
      sha512 = "5f27a56054e280b382cfa606e3c070f4e29fd4d5cadb248086fc218e4a8dba3aa65dd1342fde7a4b146def2ca7e0d723cb42f37bf9bb3b7ddbe4ab9a861769a3";
    };
  in
    super.wrapFirefox ((self.firefox-bin-unwrapped.override {
      generated = {
        inherit version sources;
      };
    }).overrideAttrs (old: {src = super.fetchurl sources;}))
    common;
  firefox-esr = let
    version = "140.5.0esr";
    sources = {
      url = "https://download.cdn.mozilla.net/pub/firefox/releases/140.5.0esr/linux-aarch64/en-US/firefox-140.5.0esr.tar.xz";
      sha512 = "5f27a56054e280b382cfa606e3c070f4e29fd4d5cadb248086fc218e4a8dba3aa65dd1342fde7a4b146def2ca7e0d723cb42f37bf9bb3b7ddbe4ab9a861769a3";
    };
  in
    super.wrapFirefox ((self.firefox-bin-unwrapped.override {
      generated = {
        inherit version sources;
      };
    }).overrideAttrs (old: {src = super.fetchurl sources;}))
    common;
  firefox-devel = let
    version = "146.0b3";
    sources = {
      url = "https://download.cdn.mozilla.net/pub/firefox/releases/146.0b3/linux-aarch64/en-US/firefox-146.0b3.tar.xz";
      sha512 = "17a645fb52accfa7490f0ee6afebda89c664aa85ad09fd351f42203f0100b060360ee75b971a84d569975279cac10f6d79b8ca6288aab0a0079c9a36dd15f9df";
    };
  in
    super.wrapFirefox ((self.firefox-bin-unwrapped.override {
      generated = {
        inherit version sources;
      };
    }).overrideAttrs (old: {src = super.fetchurl sources;}))
    common;
}
