#!/usr/bin/env bash

set -euo pipefail

export CURL_CA_BUNDLE=/etc/ssl/certs/ca-certificates.crt

JSON_FILE=$(mktemp)
curl -o $JSON_FILE -s https://product-details.mozilla.org/1.0/firefox_versions.json
LATEST_FIREFOX_VERSION=$(cat $JSON_FILE |jq -r .LATEST_FIREFOX_VERSION)
LATEST_FIREFOX_DEVEL_VERSION=$(cat $JSON_FILE |jq -r .LATEST_FIREFOX_DEVEL_VERSION)
LATEST_FIREFOX_ESR_VERSION=$(cat $JSON_FILE |jq -r .FIREFOX_ESR)
UPDATED=0

if [[ -z "$LATEST_FIREFOX_VERSION" || -z "$LATEST_FIREFOX_DEVEL_VERSION" || -z "$LATEST_FIREFOX_ESR_VERSION" ]]; then
    echo Bad firefox_versions.json: $JSON_FILE
    exit 1
fi

ARCHES="x86_64 aarch64"

for ARCH in $ARCHES; do
LATEST_FIREFOX_SHA512SUM=$(curl -s https://download.cdn.mozilla.net/pub/firefox/releases/${LATEST_FIREFOX_VERSION}/SHA512SUMS | awk '$2 == "linux-'$ARCH'/en-US/firefox-'${LATEST_FIREFOX_VERSION}'.tar.xz" { print $1; }')
LATEST_FIREFOX_DEVEL_SHA512SUM=$(curl -s https://download.cdn.mozilla.net/pub/firefox/releases/${LATEST_FIREFOX_DEVEL_VERSION}/SHA512SUMS | awk '$2 == "linux-'$ARCH'/en-US/firefox-'${LATEST_FIREFOX_DEVEL_VERSION}'.tar.xz" { print $1; }')
LATEST_FIREFOX_ESR_SHA512SUM=$(curl -s https://download.cdn.mozilla.net/pub/firefox/releases/${LATEST_FIREFOX_VERSION}/SHA512SUMS | awk '$2 == "linux-'$ARCH'/en-US/firefox-'${LATEST_FIREFOX_VERSION}'.tar.xz" { print $1; }')

if [[ -z "$LATEST_FIREFOX_SHA512SUM" || -z "$LATEST_FIREFOX_DEVEL_SHA512SUM" || -z "$LATEST_FIREFOX_ESR_SHA512SUM" ]]; then
    echo Missing checksums
    exit 1
fi

LATEST_FIREFOX_TARBALL="https://download.cdn.mozilla.net/pub/firefox/releases/${LATEST_FIREFOX_VERSION}/linux-$ARCH/en-US/firefox-${LATEST_FIREFOX_VERSION}.tar.xz"
LATEST_FIREFOX_DEVEL_TARBALL="https://download.cdn.mozilla.net/pub/firefox/releases/${LATEST_FIREFOX_DEVEL_VERSION}/linux-$ARCH/en-US/firefox-${LATEST_FIREFOX_DEVEL_VERSION}.tar.xz"
LATEST_FIREFOX_ESR_TARBALL="https://download.cdn.mozilla.net/pub/firefox/releases/${LATEST_FIREFOX_ESR_VERSION}/linux-$ARCH/en-US/firefox-${LATEST_FIREFOX_ESR_VERSION}.tar.xz"

OVERLAY_FILE=$(mktemp)

cat <<EOF |alejandra >$OVERLAY_FILE
## autogenerated
self: super:
let
  common = {
    applicationName = "firefox";
    pname = "firefox-bin";
  };
in {
  firefox-stable = let
    version = "$LATEST_FIREFOX_VERSION";
    sources = {
      url = "$LATEST_FIREFOX_TARBALL";
      sha512 = "$LATEST_FIREFOX_SHA512SUM";
    };
  in super.wrapFirefox ((self.firefox-bin-unwrapped.override {
    generated = {
      inherit version sources;
    };
  }).overrideAttrs (old: { src = super.fetchurl sources; }))
  common;
  firefox-esr = let
    version = "$LATEST_FIREFOX_ESR_VERSION";
    sources = {
      url = "$LATEST_FIREFOX_ESR_TARBALL";
      sha512 = "$LATEST_FIREFOX_ESR_SHA512SUM";
    };
  in super.wrapFirefox ((self.firefox-bin-unwrapped.override {
    generated = {
      inherit version sources;
    };
  }).overrideAttrs (old: { src = super.fetchurl sources; }))
  common;
  firefox-devel = let
    version = "$LATEST_FIREFOX_DEVEL_VERSION";
    sources = {
      url = "$LATEST_FIREFOX_DEVEL_TARBALL";
      sha512 = "$LATEST_FIREFOX_DEVEL_SHA512SUM";
    };
  in super.wrapFirefox ((self.firefox-bin-unwrapped.override {
    generated = {
      inherit version sources;
    };
  }).overrideAttrs (old: { src = super.fetchurl sources; }))
  common;
}
EOF

NIX_FILE=${ARCH}-linux.nix

if ! test -f ${NIX_FILE} || ! diff -q $OVERLAY_FILE ${NIX_FILE} >/dev/null; then
  cat $OVERLAY_FILE >${NIX_FILE}
  UPDATED=1
  if ! [[ "${CI:-false}" = true ]]; then
    git add ${NIX_FILE}
  fi
  rm -f $OVERLAY_FILE
fi
done

if [[ $UPDATED = 1 ]]; then
  if ! [[ "${CI:-false}" = true ]]; then
    git commit -m '[automated] Update'
  else
    echo UPDATED=1 >>$GITHUB_OUTPUT
  fi
else
  if [[ "${CI:-false}" = true ]]; then
    echo "::notice no update available"
    echo UPDATED=0 >>$GITHUB_OUTPUT
  fi
fi

rm -f $JSON_FILE
