## autogenerated
self: super: let
  common = {
    applicationName = "firefox";
    pname = "firefox-bin";
  };
in {
  firefox-stable = let
    version = "152.0.3";
    sources = {
      url = "https://download.cdn.mozilla.net/pub/firefox/releases/152.0.3/linux-x86_64/en-US/firefox-152.0.3.tar.xz";
      sha512 = "def2fd4dca58ce3323f59fd37845370b7ec0cfe5c98fd79c377d4130a05af8b5e9478d46df3e5acdd20e6fb3a95212d65b3e8bb63e28ce4835f886c68d9d5888";
    };
  in
    super.wrapFirefox ((self.firefox-bin-unwrapped.override {
      generated = {
        inherit version sources;
      };
    }).overrideAttrs (old: {src = super.fetchurl sources;}))
    common;
  firefox-esr = let
    version = "140.12.0esr";
    sources = {
      url = "https://download.cdn.mozilla.net/pub/firefox/releases/140.12.0esr/linux-x86_64/en-US/firefox-140.12.0esr.tar.xz";
      sha512 = "def2fd4dca58ce3323f59fd37845370b7ec0cfe5c98fd79c377d4130a05af8b5e9478d46df3e5acdd20e6fb3a95212d65b3e8bb63e28ce4835f886c68d9d5888";
    };
  in
    super.wrapFirefox ((self.firefox-bin-unwrapped.override {
      generated = {
        inherit version sources;
      };
    }).overrideAttrs (old: {src = super.fetchurl sources;}))
    common;
  firefox-devel = let
    version = "153.0b4";
    sources = {
      url = "https://download.cdn.mozilla.net/pub/firefox/releases/153.0b4/linux-x86_64/en-US/firefox-153.0b4.tar.xz";
      sha512 = "2bb124135e02b13fb494d40dbba9e9ca0f166d41c0c4ca60e6a62e93136820959e919cb335b9d056e7fbe61a92b7b98eb1775b9ebce83321726083f2de598c45";
    };
  in
    super.wrapFirefox ((self.firefox-bin-unwrapped.override {
      generated = {
        inherit version sources;
      };
    }).overrideAttrs (old: {src = super.fetchurl sources;}))
    common;
}
