## autogenerated
self: super: let
  common = {
    applicationName = "firefox";
    pname = "firefox-bin";
  };
in {
  firefox-stable = let
    version = "151.0.2";
    sources = {
      url = "https://download.cdn.mozilla.net/pub/firefox/releases/151.0.2/linux-x86_64/en-US/firefox-151.0.2.tar.xz";
      sha512 = "e423fffe8b6fb9d0f5e9c8804e4dca5c2d709e8c4c998bd42eaf949a0f4c42a2c1679e9d6c8ba0b171354023b68cba9fefcea7269352bd3ea7b28d8e1dc792fd";
    };
  in
    super.wrapFirefox ((self.firefox-bin-unwrapped.override {
      generated = {
        inherit version sources;
      };
    }).overrideAttrs (old: {src = super.fetchurl sources;}))
    common;
  firefox-esr = let
    version = "140.11.0esr";
    sources = {
      url = "https://download.cdn.mozilla.net/pub/firefox/releases/140.11.0esr/linux-x86_64/en-US/firefox-140.11.0esr.tar.xz";
      sha512 = "e423fffe8b6fb9d0f5e9c8804e4dca5c2d709e8c4c998bd42eaf949a0f4c42a2c1679e9d6c8ba0b171354023b68cba9fefcea7269352bd3ea7b28d8e1dc792fd";
    };
  in
    super.wrapFirefox ((self.firefox-bin-unwrapped.override {
      generated = {
        inherit version sources;
      };
    }).overrideAttrs (old: {src = super.fetchurl sources;}))
    common;
  firefox-devel = let
    version = "152.0b4";
    sources = {
      url = "https://download.cdn.mozilla.net/pub/firefox/releases/152.0b4/linux-x86_64/en-US/firefox-152.0b4.tar.xz";
      sha512 = "4bc74940fb6fe3b740183d8731ae15912fe48608f755f31eba8500b4c7a5f6b3010a277cc0629f4be9fb77f419405dae06982468ed105dd0d9d45b403c994d8b";
    };
  in
    super.wrapFirefox ((self.firefox-bin-unwrapped.override {
      generated = {
        inherit version sources;
      };
    }).overrideAttrs (old: {src = super.fetchurl sources;}))
    common;
}
