## autogenerated
self: super: let
  common = {
    applicationName = "firefox";
    pname = "firefox-bin";
  };
in {
  firefox-stable = let
    version = "145.0.1";
    sources = {
      url = "https://download.cdn.mozilla.net/pub/firefox/releases/145.0.1/linux-x86_64/en-US/firefox-145.0.1.tar.xz";
      sha512 = "f347d6529d78c75d926c4407bab052768da14faf31430cb2ff1e5626963011a84192afef1c039519050861b2fd28d34ca4a9f8e2a67676109a5ef115e395ce8c";
    };
  in
    super.wrapFirefox ((self.firefox-bin-unwrapped.override {
      generated = {
        inherit version sources;
      };
    }).overrideAttrs (old: {src = super.fetchurl sources;}))
    common;
  firefox-esr = let
    version = "140.5.0esr";
    sources = {
      url = "https://download.cdn.mozilla.net/pub/firefox/releases/140.5.0esr/linux-x86_64/en-US/firefox-140.5.0esr.tar.xz";
      sha512 = "f347d6529d78c75d926c4407bab052768da14faf31430cb2ff1e5626963011a84192afef1c039519050861b2fd28d34ca4a9f8e2a67676109a5ef115e395ce8c";
    };
  in
    super.wrapFirefox ((self.firefox-bin-unwrapped.override {
      generated = {
        inherit version sources;
      };
    }).overrideAttrs (old: {src = super.fetchurl sources;}))
    common;
  firefox-devel = let
    version = "146.0b5";
    sources = {
      url = "https://download.cdn.mozilla.net/pub/firefox/releases/146.0b5/linux-x86_64/en-US/firefox-146.0b5.tar.xz";
      sha512 = "476e8756438c63274cc58da54a2b4d73daa0febce1df77b4f9d214340daca9d99814cd6fe39918b24271c1dfcb4725dbd07e18a7e95e3f274a615e9855c8efad";
    };
  in
    super.wrapFirefox ((self.firefox-bin-unwrapped.override {
      generated = {
        inherit version sources;
      };
    }).overrideAttrs (old: {src = super.fetchurl sources;}))
    common;
}
