name: Refresh firefox versions
on:
  schedule:
    - cron: "11 */6 * * *"
permissions:
  contents: write
jobs:
  refresh-firefox:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixpkgs-unstable
      - name: update version
        id: update_versions
        run: |
          nix-env -f '<nixpkgs>' -iA curlMinimal jq alejandra
          cd ${{ github.workspace }}
          ./update-versions.sh
          git diff
      - uses: EndBug/add-and-commit@v9
        if: steps.update_versions.outputs.UPDATED == 1
        with:
          add: 'overlay.nix'
          default_author: github_actions
          message: '[automated] Update'
          push: true
