name: Refresh firefox versions
on:
  workflow_dispatch:
  schedule:
    - cron: "11 */6 * * *"
permissions:
  contents: write
jobs:
  refresh-firefox:
    runs-on: ubuntu-latest
    permissions:
      id-token: "write"
      contents: "write"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - uses: "DeterminateSystems/determinate-nix-action@v3"
      - name: update version
        id: update_versions
        run: |
          nix-env -f '<nixpkgs>' -iA curlMinimal jq alejandra
          cd ${{ github.workspace }}
          ./update-versions.sh
          git diff
      - uses: EndBug/add-and-commit@v9
        id: commit_step
        if: steps.update_versions.outputs.UPDATED == 1
        with:
          add: [ 'aarch64-linux.nix', 'x86_64-linux.nix' ]
          default_author: github_actions
          message: '[automated] Update'
          push: true
      - uses: "DeterminateSystems/flakehub-push@main"
        if: steps.commit_step.outputs.pushed
        with:
          name: "wahjava/ff-overlay"
          rolling: true
          visibility: "public"
          include-output-paths: true
